"""
Domain schemas split by module for better modularity.
"""
from . import core
from . import identity
from . import organizations
from . import placement
from . import cv
from . import calendar
from . import governance

# Re-export all schemas for backward compatibility
from .identity import (
    UserRead,
    UserUpdate,
    ProfileSwitchRequest,
    ActiveProfileContext,
)
from .organizations import (
    InstitutionRead,
    CompanyRead,
    BatchRead,
    ProgramRead,
    BusinessUnitRead,
    InstitutionStructureRead,
    InstitutionAboutRead,
    CompanyAboutRead,
    CompanyFunctionRead,
    CompanyDesignationRead,
    InstitutionDegreeRead,
    InstitutionCertificationRead,
    BusinessUnitCreate,
    CompanyFunctionCreate,
    CompanyDesignationCreate,
    InstitutionDegreeCreate,
    InstitutionCertificationCreate,
)
from .core import (
    ResponseSchema,
    InstitutionSchema,
    InstitutionCreateSchema,
    InstitutionUpdateSchema,
    ProgramSchema,
    ProgramCreateSchema,
    ProgramUpdateSchema,
    BatchSchema,
    BatchCreateSchema,
    BatchUpdateSchema,
    UserSchema,
    UserProfileSchema,
    UserCreateSchema,
    UserUpdateSchema,
    InstitutionLinkSchema,
    OrganizationLinkSchema,
    UserProfileResponseSchema,
    UserProfileChangeRequestSchema,
    UserProfileChangeRequestCreateSchema,
    UserProfileChangeRequestReviewSchema,
    CompanySchema,
    CompanyCreateSchema,
    CompanyUpdateSchema,
    PermissionSchema,
    RoleSchema,
    RoleCreateSchema,
    RoleUpdateSchema,
    ProfileSchema,
    ProfileCreateSchema,
    ProfileUpdateSchema,
    LoginResponseSchema,
    SwitchProfileRequest,
)
from .placement import (
    JobSchema,
    JobCreateSchema,
    JobUpdateSchema,
    CycleSchema,
    CycleCreateSchema,
    CycleUpdateSchema,
    ShortlistSchema,
    ShortlistCreateSchema,
    OfferSchema,
    OfferCreateSchema,
    HistoricalHireSchema,
    WorkflowTemplateSchema,
    WorkflowTemplateCreateSchema,
    WorkflowTemplateUpdateSchema,
    WorkflowTemplateApplySchema,
    WorkflowTemplateStageSchema,
    WorkflowTemplateStageCreateSchema,
    WorkflowSchema,
    WorkflowCreateSchema,
    WorkflowUpdateSchema,
    WorkflowStageSchema,
    WorkflowStageCreateSchema,
    WorkflowStageUpdateSchema,
    ApplicationSchema,
    ApplicationCreateSchema,
    ApplicationUpdateSchema,
    ApplicationStageProgressSchema,
    ApplicationTimelineEventSchema,
    ApplicationAttachmentSchema,
    ApplicationAttachmentCreateSchema,
    BulkProgressStudentsSchema,
)
from .cv import (
    PageConfigSchema,
    TypographyConfigSchema,
    SpacingConfigSchema,
    OverflowPolicySchema,
    FieldConfigSchema,
    EntryTypeConfigSchema,
    SectionConfigSchema,
    TemplateConfigSchema,
    CVTemplateSchema,
    CVTemplateCreateSchema,
    CVTemplateUpdateSchema,
    CVTemplatePublishSchema,
    CVSchema,
    CVCreateSchema,
    CVUpdateSchema,
    CVVerificationSchema,
)
from .calendar import (
    CalendarSlotSchema,
    CalendarSlotCreateSchema,
    CalendarSlotUpdateSchema,
    TimetableBlockSchema,
    TimetableBlockCreateSchema,
    TimetableBlockUpdateSchema,
    SlotBookingSchema,
    SlotBookingCreateSchema,
)
from .governance import (
    PolicySchema,
    PolicyCreateSchema,
    PolicyUpdateSchema,
    PolicyTemplateApplySchema,
    PolicyTemplateAssignInstitutionSchema,
    PolicyProposalSchema,
    ApplicationRequestSchema,
    ApplicationRequestCreateSchema,
    WorkflowApprovalSchema,
    WorkflowApprovalCreateSchema,
    WorkflowApprovalUpdateSchema,
    NotificationSchema,
    NotificationCreateSchema,
    JDSubmissionSchema,
    JDSubmissionCreateSchema,
)
