/**
 * Lucide icon mapping for Ithras design system.
 * Use these names with the Icon component.
 * Mapping: dashboard=LayoutGrid, workflows=Workflow, analytics=BarChart3, etc.
 */
import {
  LayoutGrid,
  Home,
  Workflow,
  BarChart3,
  LineChart,
  Users,
  UserRound,
  Building2,
  GraduationCap,
  School,
  CalendarDays,
  Settings,
  Search,
  SlidersHorizontal,
  Bell,
  CircleUser,
  Upload,
  Download,
  CheckCheck,
  BadgeCheck,
  AlertCircle,
  TriangleAlert,
  CheckCircle2,
  Archive,
  FileText,
  ScrollText,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Mail,
  Briefcase,
  BookOpen,
  ExternalLink,
  MoreHorizontal,
  LogOut,
  Play,
  HelpCircle,
} from 'lucide-react';

export const iconMap = {
  dashboard: LayoutGrid,
  home: Home,
  workflows: Workflow,
  analytics: BarChart3,
  lineChart: LineChart,
  candidates: Users,
  user: UserRound,
  companies: Building2,
  institutions: GraduationCap,
  school: School,
  calendar: CalendarDays,
  settings: Settings,
  search: Search,
  filters: SlidersHorizontal,
  notifications: Bell,
  profile: CircleUser,
  upload: Upload,
  download: Download,
  approvals: CheckCheck,
  badgeCheck: BadgeCheck,
  error: AlertCircle,
  warning: TriangleAlert,
  success: CheckCircle2,
  archive: Archive,
  audit: FileText,
  logs: ScrollText,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  mail: Mail,
  briefcase: Briefcase,
  bookOpen: BookOpen,
  externalLink: ExternalLink,
  more: MoreHorizontal,
  logout: LogOut,
  play: Play,
  help: HelpCircle,
};
